version: '3.8'
services:
  db:
    image: postgres:13
    container_name: AI-TECHNICAL-TEST-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AI-TECHNICAL-TEST
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: AI-TECHNICAL-TEST-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
