# Establecer la imagen base
FROM node:18 AS build

# Crear el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de configuración y dependencias
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Construir la aplicación
RUN npm run build

# Crear una imagen mínima para servir la aplicación
FROM nginx:1.23-alpine

# Copiar los archivos generados en la fase de build al contenedor Nginx
COPY --from=build /app/out /usr/share/nginx/html

# Exponer el puerto para el servidor Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]